### PR TITLE
Added support for new config files

### PR DESCRIPTION
**Pull request by astronautlevel2**
Addresses issue #7 

Kind of messy switch statement looks for config files in this order of priority:
/arnupdate.cfg
/aurei/arnupdate.cfg
/3ds/arnupdate.cfg

### CODE REVIEW

**Comment by Hamcha** [comment]
Can you rewrite that using a loop instead? If you don't I'll just do it when I'll be free anyway (I'm quite busy this weekend).

**Comment by astronautlevel2** [comment]
Sure, I'll get to it tonight.

**Comment by astronautlevel2** [comment]
Wait to merge this, it may cause a bug with the arm9 payload not loading properly

**Comment by Hamcha** [comment]
Commited to master

**Pull request closed without merging**
